# Keybinds
# Defining this table replaces the built-in bind set, so every active bind that
# should remain available is listed here.
# Syntax: https://docs.noctalia.dev/umbriel/keybinds/
# Actions: https://docs.noctalia.dev/umbriel/actions/
[keybinds]

# Applications and session
"Mod+T" = { action = "spawn:$TERMINAL", repeat = false }
"Mod+B" = { action = "spawn:$BROWSER", repeat = false }
"Mod+E" = { action = "spawn:$EXPLORER", repeat = false }
"Mod+Space" = "spawn:noctalia msg panel-toggle launcher"
"Mod+Shift+Space" = { action = "spawn:noctalia msg panel-toggle control-center", repeat = false }
"Mod+Q" = { action = "window-close", repeat = false }
"Mod+Escape" = "session-quit"
"Mod+Shift+Escape" = { action = "shortcuts-inhibit-toggle", allow_when_inhibited = true, repeat = false }
"Mod+Shift+S" = "spawn:noctalia msg screenshot-region"

# Focus and movement
"Mod+H" = "window-focus-left"
"Mod+J" = "window-focus-down"
"Mod+K" = "window-focus-up"
"Mod+L" = "window-focus-right"

"Mod+Shift+H" = "column-move-left"
"Mod+Shift+J" = "window-move-down"
"Mod+Shift+K" = "window-move-up"
"Mod+Shift+L" = "column-move-right"

"Mod+Ctrl+H" = "output-focus-left"
"Mod+Ctrl+L" = "output-focus-right"

"Mod+Shift+Ctrl+H" = "window-move-to-output-left"
"Mod+Shift+Ctrl+L" = "window-move-to-output-right"

# Window state and layout
"Mod+Minus" = "window-modify-primary-extent:-0.1"
"Mod+Equal" = "window-modify-primary-extent:0.1"
"Mod+Shift+Minus" = "window-modify-secondary-extent:-0.1"
"Mod+Shift+Equal" = "window-modify-secondary-extent:0.1"

#"Mod+F" = { action = "window-toggle-fullscreen", repeat = false }
"Mod+F" = { action = "window-toggle-floating", repeat = false }
"Mod+Shift+F" = { action = "window-focus-switch-floating", repeat = false }
"Mod+P" = { action = "window-toggle-pinned", repeat = false }
"Mod+M" = { action = "window-toggle-maximize", repeat = false }
"Mod+R" = "window-cycle-primary-extent"
"Mod+Shift+R" = "window-cycle-primary-extent-back"
"Mod+Comma" = "window-consume-left"
"Mod+Period" = "window-consume-right"
"Mod+W" = { action = "column-toggle-tabbed", repeat = false }
"Mod+Alt+Right" = "column-focus-tab-next"
"Mod+Alt+Left" = "column-focus-tab-previous"
"Mod+O" = { action = "overview-toggle", repeat = false }

# Workspaces
"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"

